Repository knurling-rs/defmt, pull requests merged in 2021-06, with the labels that each got.

#505 [1/n] - Logger trait v2.
  firmware/defmt-itm/src/lib.rs
  firmware/defmt-rtt/src/lib.rs
  firmware/defmt-semihosting/src/lib.rs
  macros/src/lib.rs
  src/export.rs
  src/formatter.rs
  src/lib.rs
  src/traits.rs
  tests/basic_usage.rs
Labels: breaking change

#508 [5/n] Format trait v2
  book/src/ser-format.md
  decoder/src/decoder.rs
  decoder/src/frame.rs
  decoder/src/lib.rs
  defmt.x.in
  firmware/qemu/src/bin/log.out
  firmware/qemu/src/bin/log.release.out
  firmware/qemu/src/bin/log.rs
  macros/src/lib.rs
  parser/src/types.rs
  src/export.rs
  src/formatter.rs
  src/impls/adapter.rs
  src/impls/alloc_.rs
  src/impls/arrays.rs
  src/impls/core_/mod.rs
  src/impls/mod.rs
  src/impls/primitives.rs
  src/impls/tuples.rs
  src/lib.rs
  src/traits.rs
  tests/encode.rs
  tests/ui/fmt-for-loop.rs
  tests/ui/fmt-for-loop.stderr
  tests/ui/fmt-twice.rs
  tests/ui/fmt-twice.stderr
  tests/ui/write-for-loop.rs
  tests/ui/write-for-loop.stderr
  tests/ui/write-twice.rs
  tests/ui/write-twice.stderr
Labels: pr waits on: author

#359 Implement precedence of inner display hint
  decoder/src/frame.rs
  decoder/src/lib.rs
  firmware/qemu/src/bin/hints_inner.out
  firmware/qemu/src/bin/hints_inner.release.out
  firmware/qemu/src/bin/hints_inner.rs
  macros/src/lib.rs
  xtask/src/main.rs
Labels: pr waits on: review
